In [5]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [6]:
#2. Print the NUMPY version and the configuration.
print(np.version.version) 

1.15.2


In [35]:
"""
#3. Generate a 2x3x5 3-dimensional array with random values. 
   Assign the array to variable "a"
   Challenge: there are at least three easy ways that use numpy to generate random arrays. 
   How many ways can you find?
#4. Print a.
"""

a = np.random.random((2,3,5))
print(a)
print(a.shape)

[[[0.49432597 0.33933949 0.48115248 0.29323061 0.85451859]
  [0.29669582 0.57167282 0.90650097 0.47025012 0.13400812]
  [0.74390501 0.3676328  0.13196446 0.8352177  0.49675397]]

 [[0.88723795 0.2365484  0.16386569 0.4928024  0.07904439]
  [0.62571099 0.44512095 0.92761494 0.93270651 0.23938251]
  [0.60278881 0.53339143 0.81890682 0.11308907 0.40798988]]]
(2, 3, 5)


In [37]:
"""
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
   Assign the array to variable "b"

#6. Print b.
"""

lst = [[(1,1,1),(1,1,1)],[(1,1,1),(1,1,1)],[(1,1,1),(1,1,1)],[(1,1,1),(1,1,1)],[(1,1,1),(1,1,1)]]
b = np.array(lst)
print(b)
print(b.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(5, 2, 3)


In [30]:
lst_lst1 = [[(2,3,4),(2,3,4)],[(2,3,4),(2,3,4)]]
c = np.array(lst_lst1)
print(c)
print(c.shape)

[[[2 3 4]
  [2 3 4]]

 [[2 3 4]
  [2 3 4]]]
(2, 2, 3)


In [38]:
lst = [[(1,1,1),(1,1,1)],[(1,1,1),(1,1,1)],[(1,1,1),(1,1,1)],[(1,1,1),(1,1,1)],[(1,1,1),(1,1,1)]]
print(lst)

[[(1, 1, 1), (1, 1, 1)], [(1, 1, 1), (1, 1, 1)], [(1, 1, 1), (1, 1, 1)], [(1, 1, 1), (1, 1, 1)], [(1, 1, 1), (1, 1, 1)]]


In [41]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)
print(b.size)

print(a.shape)
print(b.shape)

30
30
(2, 3, 5)
(5, 2, 3)


In [61]:
#8. Are you able to add a and b? Why or why not?
#  print(np.add(a, b))

In [77]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b,(1,2,0))
print(c)
print(c.shape)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)


In [73]:
#attempt1 
ccc = np.transpose(b)
print(ccc)
print(ccc.shape)

cc = np.moveaxis(ccc, 0, 1)
print(cc)
print(cc.shape)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]
(3, 2, 5)
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)


In [74]:
#attempt2 
cccc = np.moveaxis(b, 0, -1)
print(cccc)
print(cccc.shape)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)


In [79]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a, c)
print(d)

[[[1.49432597 1.33933949 1.48115248 1.29323061 1.85451859]
  [1.29669582 1.57167282 1.90650097 1.47025012 1.13400812]
  [1.74390501 1.3676328  1.13196446 1.8352177  1.49675397]]

 [[1.88723795 1.2365484  1.16386569 1.4928024  1.07904439]
  [1.62571099 1.44512095 1.92761494 1.93270651 1.23938251]
  [1.60278881 1.53339143 1.81890682 1.11308907 1.40798988]]]


In [80]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)

[[[0.49432597 0.33933949 0.48115248 0.29323061 0.85451859]
  [0.29669582 0.57167282 0.90650097 0.47025012 0.13400812]
  [0.74390501 0.3676328  0.13196446 0.8352177  0.49675397]]

 [[0.88723795 0.2365484  0.16386569 0.4928024  0.07904439]
  [0.62571099 0.44512095 0.92761494 0.93270651 0.23938251]
  [0.60278881 0.53339143 0.81890682 0.11308907 0.40798988]]]
[[[1.49432597 1.33933949 1.48115248 1.29323061 1.85451859]
  [1.29669582 1.57167282 1.90650097 1.47025012 1.13400812]
  [1.74390501 1.3676328  1.13196446 1.8352177  1.49675397]]

 [[1.88723795 1.2365484  1.16386569 1.4928024  1.07904439]
  [1.62571099 1.44512095 1.92761494 1.93270651 1.23938251]
  [1.60278881 1.53339143 1.81890682 1.11308907 1.40798988]]]


In [88]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a,c)
print(e)
print(e.shape)

[[[0.49432597 0.33933949 0.48115248 0.29323061 0.85451859]
  [0.29669582 0.57167282 0.90650097 0.47025012 0.13400812]
  [0.74390501 0.3676328  0.13196446 0.8352177  0.49675397]]

 [[0.88723795 0.2365484  0.16386569 0.4928024  0.07904439]
  [0.62571099 0.44512095 0.92761494 0.93270651 0.23938251]
  [0.60278881 0.53339143 0.81890682 0.11308907 0.40798988]]]
(2, 3, 5)


In [84]:
#13. Does e equal to a? Why or why not?
print(e)
print(a)
e == a

[[[0.49432597 0.33933949 0.48115248 0.29323061 0.85451859]
  [0.29669582 0.57167282 0.90650097 0.47025012 0.13400812]
  [0.74390501 0.3676328  0.13196446 0.8352177  0.49675397]]

 [[0.88723795 0.2365484  0.16386569 0.4928024  0.07904439]
  [0.62571099 0.44512095 0.92761494 0.93270651 0.23938251]
  [0.60278881 0.53339143 0.81890682 0.11308907 0.40798988]]]
[[[0.49432597 0.33933949 0.48115248 0.29323061 0.85451859]
  [0.29669582 0.57167282 0.90650097 0.47025012 0.13400812]
  [0.74390501 0.3676328  0.13196446 0.8352177  0.49675397]]

 [[0.88723795 0.2365484  0.16386569 0.4928024  0.07904439]
  [0.62571099 0.44512095 0.92761494 0.93270651 0.23938251]
  [0.60278881 0.53339143 0.81890682 0.11308907 0.40798988]]]


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [105]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max) 
print(d_min)
print(d_mean)

1.9327065091238562
1.0790443889150594
1.4974456561478349


In [146]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f = np.empty([2,3,5])
print(f)

[[[0.49432597 0.33933949 0.48115248 0.29323061 0.85451859]
  [0.29669582 0.57167282 0.90650097 0.47025012 0.13400812]
  [0.74390501 0.3676328  0.13196446 0.8352177  0.49675397]]

 [[0.88723795 0.2365484  0.16386569 0.4928024  0.07904439]
  [0.62571099 0.44512095 0.92761494 0.93270651 0.23938251]
  [0.60278881 0.53339143 0.81890682 0.11308907 0.40798988]]]


In [158]:
for a0, block in enumerate(d):
     for a1, line in enumerate(block):
         for a2, column in enumerate (line):
             if d[a0,a1,a2] == d_mean:
                    f[a0,a1,a2] = 50
             if d[a0,a1,a2] == d_max:
                    f[a0,a1,a2] = 100
             if d[a0,a1,a2] == d_min:
                    f[a0,a1,a2] = 0
             if (d[a0,a1,a2] > d_min) and (d[a0,a1,a2] < d_mean):
                    f[a0,a1,a2] = 25
             if (d[a0,a1,a2] > d_mean) and (d[a0,a1,a2] < d_max):
                    f[a0,a1,a2] = 75

[[[1.49432597 1.33933949 1.48115248 1.29323061 1.85451859]
  [1.29669582 1.57167282 1.90650097 1.47025012 1.13400812]
  [1.74390501 1.3676328  1.13196446 1.8352177  1.49675397]]

 [[1.88723795 1.2365484  1.16386569 1.4928024  1.07904439]
  [1.62571099 1.44512095 1.92761494 1.93270651 1.23938251]
  [1.60278881 1.53339143 1.81890682 1.11308907 1.40798988]]]
[[[ 25.  25.  25.  25.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75.  25.  25.  25.   0.]
  [ 75.  25.  75. 100.  25.]
  [ 75.  75.  75.  25.  25.]]]


In [160]:
#17
print(d)
print(f)

[[[1.49432597 1.33933949 1.48115248 1.29323061 1.85451859]
  [1.29669582 1.57167282 1.90650097 1.47025012 1.13400812]
  [1.74390501 1.3676328  1.13196446 1.8352177  1.49675397]]

 [[1.88723795 1.2365484  1.16386569 1.4928024  1.07904439]
  [1.62571099 1.44512095 1.92761494 1.93270651 1.23938251]
  [1.60278881 1.53339143 1.81890682 1.11308907 1.40798988]]]
[[[ 25.  25.  25.  25.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75.  25.  25.  25.   0.]
  [ 75.  25.  75. 100.  25.]
  [ 75.  75.  75.  25.  25.]]]
